### ISSUE TITLE
dirforest

### ISSUE THREAD

**Issue by NorfairKing** [chessai/fs#1]
I don't mean to spam you, but you might enjoy https://github.com/NorfairKing/dirforest

**Comment by chessai** [comment]
Not spam. This is interesting and useful, thanks!

I want to provide two approaches here - tree structure that doesn't respect
references, and a DAG that does. Often you want DAGs to represent your
filesystem because of references to other files. This will then hopefully
be useful in compilers and other tools I have in mind that could use it.
Also symlinks potentially need a dag too.

**Comment by NorfairKing** [comment]
Aha! Well dirforest doesn't provide a dag structure at all but It's well-tested for forest structures. I'm using it in smos: smos.cs-syd.eu so I consider it production-ready.
